import type { Metadata } from "next";
import "./globals.css";
import ClientProviders from "@/context/providers/ClientProviders";
import { PaymentProvider } from "@/context/payment-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          <PaymentProvider>{children}</PaymentProvider>
        </ClientProviders>
      </body>
    </html>
  );
}
